# -*- coding: utf-8 -*-
"""Examen1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NJu9TWivaHYno0uW62V6GeamkzedMHye

# 1.- ¿ES PRIMO?
"""

def es_primo(numero):
    if numero <= 1:
        return False
    if numero <= 3:
        return True
    if numero % 2 == 0 or numero % 3 == 0:
        return False
    i = 5
    while i * i <= numero:
        if numero % i == 0 or numero % (i + 2) == 0:
            return False
        i += 6
    return True

def main():
    numero = int(input("Ingrese un número entero: "))
    if es_primo(numero):
        print(f"{numero} es un número primo.")
    else:
        print(f"{numero} no es un número primo.")

if __name__ == "__main__":
    main()

"""# 2.- 2do Paso de: ¿Es primo?"""

def es_primo(numero):
    if numero <= 1:
        return False
    if numero <= 3:
        return True
    if numero % 2 == 0 or numero % 3 == 0:
        return False
    i = 5
    while i * i <= numero:
        if numero % i == 0 or numero % (i + 2) == 0:
            return False
        i += 6
    return True

def next_prime(n):
    numero = n + 1
    while True:
        if es_primo(numero):
            return numero
        numero += 1

def main():
    n = int(input("Ingrese un número entero: "))
    siguiente_primo = next_prime(n)
    print(f"El primer número primo mayor que {n} es {siguiente_primo}.")

if __name__ == "__main__":
    main()

"""# 3.- Contraseña random"""

import random

def generar_contrasena():
    longitud = random.randint(7, 10)
    contrasena = ""
    for _ in range(longitud):
        caracter = chr(random.randint(33, 126))
        contrasena += caracter
    return contrasena

if __name__ == "__main__":
    contrasena_generada = generar_contrasena()
    print(f"Contraseña generada: {contrasena_generada}")

"""# 4.- Mediana de 3 valores"""

def mediana_de_tres(num1, num2, num3):
    numeros = [num1, num2, num3]
    numeros.sort()
    return numeros[1]

def main():
    num1 = float(input("Ingrese el primer número: "))
    num2 = float(input("Ingrese el segundo número: "))
    num3 = float(input("Ingrese el tercer número: "))

    mediana = mediana_de_tres(num1, num2, num3)
    print(f"La mediana de los números ingresados es: {mediana}")

if __name__ == "__main__":
    main()

"""# 5.- Calcular la hipotenusa"""

import math

def calcular_hipotenusa(lado1, lado2):
    hipotenusa = math.sqrt(lado1**2 + lado2**2)
    return hipotenusa

def main():
    lado1 = float(input("Ingrese la longitud del primer lado: "))
    lado2 = float(input("Ingrese la longitud del segundo lado: "))

    hipotenusa = calcular_hipotenusa(lado1, lado2)
    print(f"La longitud de la hipotenusa es: {hipotenusa}")

if __name__ == "__main__":
    main()